-- LEGACY / ARCHIVED SQL.
-- This file belongs to an older MySQL setup and is not used by the current
-- Stage 2 MongoDB replica-set deployment.

DROP TABLE IF EXISTS system_logs;
DROP TABLE IF EXISTS citations;
DROP TABLE IF EXISTS investigations;
DROP TABLE IF EXISTS parking_events;
DROP TABLE IF EXISTS parking_spaces;
DROP TABLE IF EXISTS parking_zones;
DROP TABLE IF EXISTS vehicles;
CREATE TABLE vehicles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin VARCHAR(20) NOT NULL UNIQUE,
    manufacturer VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    year INT,
    owner_name VARCHAR(100) NOT NULL,
    owner_email VARCHAR(100),
    owner_phone VARCHAR(20),
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE parking_zones (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_name VARCHAR(100) NOT NULL UNIQUE,
    location VARCHAR(255),
    rate DECIMAL(10, 2) NOT NULL,
    daily_max_rate DECIMAL(10, 2),
    maximum_parking_minutes INT NOT NULL,
    is_enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE parking_spaces (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id INT NOT NULL,
    space_number VARCHAR(20) NOT NULL UNIQUE,
    space_type VARCHAR(20) DEFAULT 'standard',
    is_available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_spaces_zone FOREIGN KEY (zone_id) REFERENCES parking_zones(id)
);

CREATE TABLE parking_events (
    event_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id INT NOT NULL,
    zone_id INT NOT NULL,
    space_id INT NOT NULL,
    park_time TIMESTAMP NOT NULL,
    unpark_time TIMESTAMP,
    duration_minutes INT,
    amount_due DECIMAL(10, 2),
    is_paid BOOLEAN DEFAULT FALSE,
    paid_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_events_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_events_zone FOREIGN KEY (zone_id) REFERENCES parking_zones(id),
    CONSTRAINT fk_events_space FOREIGN KEY (space_id) REFERENCES parking_spaces(id)
);

CREATE TABLE citations (
    citation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id INT NOT NULL,
    zone_id INT NOT NULL,
    space_id INT NOT NULL,
    enforcer_id INT,
    citation_reason VARCHAR(255) NOT NULL,
    penalty_amount DECIMAL(10, 2) NOT NULL,
    issued_date TIMESTAMP NOT NULL,
    is_paid BOOLEAN DEFAULT FALSE,
    paid_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_citations_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_citations_zone FOREIGN KEY (zone_id) REFERENCES parking_zones(id),
    CONSTRAINT fk_citations_space FOREIGN KEY (space_id) REFERENCES parking_spaces(id)
);

CREATE TABLE investigations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peo_user_id INT NOT NULL,
    vehicle_id INT NOT NULL,
    space_id INT NOT NULL,
    result VARCHAR(32) NOT NULL,
    investigated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_investigations_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_investigations_space FOREIGN KEY (space_id) REFERENCES parking_spaces(id)
);

CREATE TABLE system_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_time TIMESTAMP NOT NULL,
    vehicle_number VARCHAR(20) NOT NULL,
    parking_space_id VARCHAR(50) NOT NULL,
    response VARCHAR(255) NOT NULL
);

